### ISSUE TITLE
ValueError: Can't clean for JSON for networkx nodes that are objects. 

### ISSUE THREAD

**Issue by besito-app** [QuantStack/ipycytoscape#115]
Execute the following in a jupyter lab notebook and you'll get 'ValueError: Can't clean for JSON'. I believe this should work, and is a bug. It works fine if I use nx.draw(G) instead of ipycytoscape. 

```
import ipycytoscape
import networkx as nx

class Node:
    def __init__(self, name):
        self.name = name

n1 = Node("node 1")
n2 = Node("node 2")
        
G = nx.Graph()

G.add_node(n1)
G.add_node(n2)

G.add_edge(n1, n2)

undirected = ipycytoscape.CytoscapeWidget()
undirected.graph.add_graph_from_networkx(G)
undirected
```

**Comment by ianhi** [comment]
Hey @besito-app good catch! Unfortunately custom objects and tuples are valid networkx nodes but don't yet work with ipycytoscape. The underlying issue is the same as https://github.com/QuantStack/ipycytoscape/issues/86. There's been some discussion on how to fix this there as well as:
https://github.com/QuantStack/ipycytoscape/pull/70#discussion_r426533510
and #45 (has a very similar example to yours)
If you're interested in trying to fix this a PR would be totally welcome (otherwise it will hopefully be fixed soon anyway) I wrote some thoughts below on how this might be fixed, and the relevant lines of code are here:
https://github.com/QuantStack/ipycytoscape/blob/139fdcdeec03f689bab6f56b7744dd253a65d08d/ipycytoscape/cytoscape.py#L378-L379

As a stopgap you can manually make the `id` in the node data a string - though you will also have to change how you add the edges. So using these lines I can get your example to render:
```python
G.add_node(n1, id=n1.name)
G.add_node(n2, id=n2.name)

G.add_edge(n1.name, n2.name)
```
@marimeireles @MridulS I'm pretty sure that always calling `str` on the node id is the correct choice as cytoscapejs requires a string as the id. But it's totally possible I'm missing something - do you think there is a better way?

From cytoscapejs docs:
> id: 'n1', // mandatory (string) id for each element, assigned automatically on undefined

We could check for a str and catch any exceptions with a helpful error saying that there needs to be a string representation of the id. As a piece of info I believe that the valid networkx options for making a networkx node are:

  -  bool
  -  int
   - float
   - tuple
  -  str
- frozenset
- custom class

All except the custom class implement `__str__` and a custom class author will just have to add `__str__`

The lines extracting the edges would also need to have `str` called on them:
https://github.com/QuantStack/ipycytoscape/blob/139fdcdeec03f689bab6f56b7744dd253a65d08d/ipycytoscape/cytoscape.py#L386-L387

**Comment by jaydonnell** [comment]
I'm having the exact same issue. Calling str() on custom objects as @ianhi suggested makes sense to me, but python isn't my primary language so 🤷 . I'm happy to work on a PR if you all think it's a reasonable direction.

**Comment by ianhi** [comment]
@jaydonnell go for it :)

I think the best way to determine if it's actually a good idea is to see if it does the following:
1. Works for custom classes that implement `__str__`
2. doesn't break any of the existing examples using networkx 
    - ideally it will work for all the valid networkx node ids
    - including a notebook with custom classes in the Examples directory would also be rad

 And feel free to open a partially finished PR if you find you need some help/feedback.

**Comment by MridulS** [comment]
Is there any specific use case for having custom classes? (unless the idea here is to mirror exactly nx.draw). The `str()` argument will make it work with ipycytoscape but we will essentially lose all the information of the object. (which should be okay if we want to make ipycytoscape compatible with hashable node objects).

If the idea here is to pass information from the Node custom object to the ipycytoscape graph object then we can do something like

``` python
import ipycytoscape

class CustomNode(ipycytoscape.Node):
    def __init__(self, i, test):
        super().__init__()
        self.data['id'] = i
        self.data['test_var'] = test

ipyGraph = ipycytoscape.CytoscapeWidget()
ipyGraph.graph.add_node(CustomNode(1, 'boo'))
```
and we can access the newly created custom nodes by something like 
```
>>> ipyGraph.graph.nodes
[CustomNode(data={'id': 1, 'test_var': 'boo'}, position={})]
```

**Comment by ianhi** [comment]
Oooh I hadn't thought about subclassing the nodes, that's clever. One issue in your example though is that you've substituted creating the graph in networkx for creating it with ipycytoscape - I think there would need to be checks in the `from_networkx` method to see if the passed node is a subclass of `Node`

> Is there any specific use case for having custom classes?

I tend to use this library for visualization and prefer to create, manipulate, and analyze graphs with networkx. There are use cases there where you might want to use a custom object as the nodes for networkx. So if you are using ipycytoscape only for visualization then losing any methods or extra state of the nodes shouldn't be an issue.

Perhaps the easiest thing to do is to check if the node is a subclass of `ipyctyoscape.Node` and otherwise call `str` on it?

**Comment by marimeireles** [comment]
Ok so yeah, if we stick to the `cytoscape` API we wouldn't really have to care about it and as @ianhi said the 

```
n1 = str(Node("node 1"))
n2 = str(Node("node 2"))
```

solution would work. But! I don't really like it, I think it's very limiting and it'd be cool if we could offer full compatibility with Nx specially seeing how many people use it. I'd say 90%+ of the use cases I'm aware of are using Nx somehow, so it'd be useful to aim for a 100% compat.

I like @MridulS solution a lot and I think it closes this issue. What do you people think?

> Perhaps the easiest thing to do is to check if the node is a subclass of ipyctyoscape.Node and otherwise call str on it?

I think a temporary fix like this might be useful.

But imo it'd be cool if we offered full support for Nx like it's kinda being discussed #89 .

**Comment by ianhi** [comment]
I agree that it makes sense to support the subclassing of Nodes. But we also need to fix the issue with Tuples which I think needs a different solution. I added the test cases that currently break to a notebook here:
https://github.com/ianhi/ipycytoscape/blob/f9aa4e2eb722993b1d3ae0c25ec4b111f58c162f/examples/NetworkX%20Example.ipynb

if you scroll down to the "Test other Node Types" section you can see the examples. In particular it seems like `Tuple`, `Frozenset`, `Custom Class`, `Custom Class (subclassing Node)` all currently break

**Comment by ianhi** [comment]
Ok how about these changes?: https://github.com/ianhi/ipycytoscape/commit/3ffac242ad6599c97192ab856ed70a293fdbc3bf

That seems to make all the examples work.

One thing that is not clear is what happens if you use a CustomNode and then change the `data['id']` after the cytoscape node has been created. This seems like something to be dealt with in typescript though, not on the python side.

**Comment by jaydonnell** [comment]
Doesn't this force peoples networkx code to depend on ipyctoscape? As a user I'd prefer to reduce dependencies rather than increase them. 

BTW, how do you run the python test suite?

**Comment by jaydonnell** [comment]
Here's a pull request that coerces the custom node object to str. 

https://github.com/QuantStack/ipycytoscape/pull/118

**Comment by ianhi** [comment]
> BTW, how do you run the python test suite?

The test suite doesn't actually have any tests in it.... It would be good check examples though.


> Doesn't this force peoples networkx code to depend on ipyctoscape?

Ideally you would be able to use the full networkx api to make you graph and have that work with ipycytoscape. I think what's being proposed is that in addition to that if you want to subclass `ipycytoscape.Node` there will be extra capabilities.

**Comment by jaydonnell** [comment]
gotcha, sorry, I missed the call to str() in your's the first time i looked at it.
