### ISSUE TITLE
Add tooltips to edges

### ISSUE THREAD

**Issue by ngthanhvinh** [QuantStack/ipycytoscape#127]
Hi, I wonder if there is a way to add tooltips to edges (to display edge weights in particular)? Right now, I can only display edge weights explicitly by styling `content: data(weight)`. I also have tried `set_tooltip_source` but it only works with nodes.

**Comment by ianhi** [comment]
Hi @ngthanhvinh good question! Sadly the answer is currently no, but it should be possible to get this working. If you or anyone else would like to have a go at implementing this I think a good approach would be to take the node tooltip code on the frontend side and generalize it work with edges as well. That code lives here:
https://github.com/QuantStack/ipycytoscape/blob/72b73c6a8bd4d352bfcf97c71a24036b1524573e/src/widget.ts#L413-L442
In particular we need to run the same code with `this.cytoscape_obj.on('click', 'edge', (e: any) => { ` to detect edge clicks instead of only node clicks.

Ideally we'd be able to replicate this example from cytoscapejs (https://cytoscape.org/cytoscape.js-popper/demo-tippy.html) The code that makes the tooltips for that example is here: https://github.com/cytoscape/cytoscape.js-popper/blob/ac9d36f0bd9c220c4e059c90f34c4c38543fb60d/demo-tippy.html#L85-L138

We could make use of the `makeTippy` function from that example and then re-use that function for both nodes and edges. We should also add a way to make permanent tooltips - though maybe that deserves it's own issue.

**Comment by ianhi** [comment]
Actually an even simpler solution is probably to just have the event listener listen to all clicks by changing the line to ` this.cytoscape_obj.on('click', (e: any) => { ` see cytoscapejs docs here: https://js.cytoscape.org/#cy.on

**Comment by ianhi** [comment]
fixed by @ngthanhvinh in #130 !
