### ISSUE TITLE
KeyError: 'nodeSpacing'

### ISSUE THREAD

**Issue by gqpj** [QuantStack/ipycytoscape#25]
When I run `Grid Example.ipynb` or `Labels example.ipynb` I get:
```
Traceback (most recent call last)
<ipython-input-5-36fb9ff467a6> in <module>
----> 1 cytoscapeobj.set_layout(name='grid')

~/miniconda3/lib/python3.7/site-packages/ipycytoscape/cytoscape.py in set_layout(self, name, nodeSpacing, edgeLengthVal, animate, randomize, maxSimulationTime, padding)
    119             dummyDict['nodeSpacing'] = nodeSpacing
    120         else:
--> 121             dummyDict['nodeSpacing'] = self.cytoscape_layout['nodeSpacing']
    122         if edgeLengthVal != None:
    123             dummyDict['edgeLengthVal'] = edgeLengthVal

KeyError: 'nodeSpacing'
```

**Comment by marimeireles** [comment]
Hum! I know this issue.
I thought I had fixed it before, but this is happening because of bug on a library we use, `traitlets`. Because of this bug you can't change individual key/values of a dictionary, you have to change it all over again, so I think the `Labels` example is doing something like this:
```
cytoscapeobj.set_layout(name='grid')
```
When it should actually be doing something like this:
```
cytoscapeobj.set_layout(name='grid', nodeSpacing=10, edgeLengthVal=10)
```
The new version I'm working now makes this issue goes away =) It should be ready by some point in this week.

For now what you can do is pass all of these three arguments every time you want to change the layout, sorry!

**Comment by marimeireles** [comment]
This is fixed and can be found on the master branch in this repo, or in the version 0.2.0 that will be released soon. I decided to postpone the new version because I wanted to add some functionalities for a project I'm contact with.
If you need help building stuff directly from git, don't hesitate to ping me [here](https://gitter.im/QuantStack/Lobby).
