### ISSUE TITLE
node id in from_networkx is always cast to int

### ISSUE THREAD

**Issue by ianhi** [QuantStack/ipycytoscape#45]
In the `add_graph_from_networkx`  method the node id is forced to be an int:
https://github.com/QuantStack/ipycytoscape/blob/59e3440d8a77efb3ecae4867e1992d400be5b96c/ipycytoscape/cytoscape.py#L194-L197

But networkx nodes can be any hashable object ([ref](https://networkx.github.io/documentation/stable/tutorial.html#what-to-use-as-nodes-and-edges)):

> The most common choices are numbers or strings, but a node can be any hashable object (except None)

for example:
```python
import ipycytoscape
import networkx as nx

class person:
    def __init__(self, name):
        self.name = name
    def __repr__(self):
        return str(self.name)
person1 = person('ian')
person2 = person('maleah')

G = nx.Graph()
G.add_node(person1)
G.add_node(person2)
G.add_edge(person1,person2)

cytoscapeobj = ipycytoscape.CytoscapeWidget()
cytoscapeobj.graph.add_graph_from_networkx(G)
```

throws a type error.

As far as I can I can tell the JSON examples use strings as ids for the nodes so I don't think it will break anything to allow more types for the from_networkx method.

**Comment by marimeireles** [comment]
Yep. That's a very good catch.
I'll add it to my backlog but feel free to tackle it too if you want to. I'm around if you have any more questions and also available [here](https://gitter.im/QuantStack/Lobby).

**Comment by ianhi** [comment]
Sounds good, I won't have time until Friday but I'll fix this then. Unfortunately being a grad student involves more than having fun contributing to open source software :(

Looking at the cytoscapejs documentation for elements ([ref](https://js.cytoscape.org/#notation/elements-json)) I think that the node id needs to be a string or at least castable to a string

>    id: 'n1', // mandatory (string) id for each element, assigned automatically on undefined

So maybe calling `repr` or `str` on the id is the correct thing to do?

**Comment by marimeireles** [comment]
>So maybe calling repr or str on the id is the correct thing to do?

I don't think so.
You're right about the `int`, it doesn't make sense to have an id that's always an `int`, but I'm afraid that you can't pass a whole object to the graph as id  because it's an unserialized object. (I just tested it).

Maybe just serializing it works? Using the [json](https://docs.python.org/3/library/json.html#module-json) module. But then, I think it'd make more sense to write something like:

```
        for node in g.nodes():
            node_instance = Node()
            node_instance.data = node
            self.nodes.append(node_instance)
```

Additionally, it's necessary to give an option to user to choose which id they want to use. Because to have a working cytoscape graph you must have an id, the rest of the attribute are optional.
We'd have to do the same for edges with `target` and `source`.

That's a fix, but maybe better solution would be to try to fit networkx class attributes in a cytoscape object.
So, if you have keywords in a networkx graph that match the keywords existent in a cytoscape graph you could make a better conversion from one to another. And the keywords that don't match could be just added to `data`.

**Comment by ianhi** [comment]
> but I'm afraid that you can't pass a whole object to the graph as id because it's an unserialized object. 

Looking back on this I'm not sure I understand what you mean here. Is this why calling `repr` or `str` is incorrect?
