### ISSUE TITLE
aggregated suggestions

### ISSUE THREAD

**Issue by ianhi** [QuantStack/ipycytoscape#46]
I want to start by saying thanks so much for this widget! I'm glad I started my current project (building and analyzing lots of graphs) now and not two months ago :) In a flurry of foolishness I was about to try to implement my own version of this widget before I found this. Which actually leads me to my first suggestion

### 1. more jupyter keywords
I spent an hour or so this morning searching around for the best way to visualize netowrkx graphs in jupyter notebooks and even after deciding I was interested in cytoscopejs I almost didn't find this widget. I found a few outdated widgets (e.g. this [google search](https://www.google.com/search?client=ubuntu&channel=fs&q=jupyterlab+widget+cytoscape&ie=utf-8&oe=utf-8)), but I only found this one because I searched in the jupyterlab extension manager for cytoscape. I don't know if this would affect anything but maybe more mentions of jupyterlab higher up in the readme. i.e. first sentence: A jupyter/jupyterlab widget for displaying ... could help with easier discovery of this repo.

### 2. Add a default style for directed graphs
I would be nice if I could give an argument to the constructor of the widget specifying that my graph was directed, and this would add the appropriate elements to the style add arrows to the edges.

### 3. link to examples directory in the README
I figured out how to style a directed graph by looking at JSON example. Leading people to this from the readme would be great

### 4. create an `add_to_style` method
If I do want to make a directed graph and want to style the edges to be directed then I need to recrete the entire default styling. A nice addition might be a method like this:
```python
def add_to_style(self, style):
    """
    Adds the given stylesheet to the current stylesheet. Existing keys will be
    overwritten
    
    Parameters
    ----------
    stylesheet: dict
    """
    for key in style:
        self.style[key] = style[key]
```

I'm open to helping out on these if you think they're useful and can provide some guidance on any conventions you'd like to be followed.

**Comment by SylvainCorlay** [comment]
Hey @ianhi thanks for opening the issue.

> I'm open to helping out on these if you think they're useful and can provide some guidance on any conventions you'd like to be followed.

That's great to hear!

On the "more jupyter keywords" thing, note that we have not yet announced / advertized the release of ipycytoscape, although the blog post should be published very soon. It should soon be easier to find - and referenced on the jupyter.org/widgets page as well.

**Comment by marimeireles** [comment]
> 1. more jupyter keywords

I never really thought about this. Please feel free to add a PR with the changes you think it'd be relevant on the README.

> 2. Add a default style for directed graphs

Great idea! I created an issue https://github.com/QuantStack/ipycytoscape/issues/48 for that one =)

> 3. link to examples directory in the README

Also created an issue for that, thanks again. https://github.com/QuantStack/ipycytoscape/issues/49

> 4. create an add_to_style method

So the problem here is a bit more annoying. It's something I tried to fix in the last version but there is a bug in the Spectate implementation that prevents us of editing lists and dictionaries. I don't remember quite well why it didn't work, but doing the same thing that I'm doing in other places see https://github.com/QuantStack/ipycytoscape/blob/master/ipycytoscape/cytoscape.py#L110 doesn't really work. If you wanna tackle that, you're super welcome too. :)

**Comment by ianhi** [comment]
### add_to_style
>bug in the Spectate implementation that prevents us of editing lists and dictionaries.

How about a convenience function like:
```python
def add_to_style(self, style):
    old_style = self.get_style()
    # integrate style into new styke
    # new_style = .....
    # ....
    self.set_style(new_style)
```

### traitlets
Is there a good resource for learning more about traitlets? I read the documentation, but I'm still a little confused as to why `spectate` is necessary. Which is to say I don't see why Traitlets objects are not mutable on their own. As python objects they seem to be, i.e. I can run:
```python
cytoscapeobj.cytoscape_style[0]['css']['background-color']='red'`
```
without an error. But this does not update the styling of the graph.

**Comment by marimeireles** [comment]
> How about a convenience function like:

I think this might work, if you use [copy](https://docs.python.org/3.8/library/copy.html) to create a new object in the end, because the problem on traitlets is updating objects, it just accepts brand new objects. It should be kind of similar to https://github.com/QuantStack/ipycytoscape/blob/8d1cc0923f14a752408b2e76a38dd349fbc6f6ce/ipycytoscape/cytoscape.py#L316-L338

I'll create an issue that relates to this issue and add some information there. Again you're super welcome to give it a try :)

Regarding traitlets, the reason why I use it it's because jupyter uses it. I don't know why they do it though... But yeah, the problem is that even though you can see the changes in the python object they're not reflected in the frontend. So if I add new nodes to a pure spectate object without making a full copy of it these changes won't be reflected in the front end.

Thanks for the observations here :)

**Comment by marimeireles** [comment]
I think the #56 is dealing with what was the last thing missing to attend here, right @ianhi?
Can we close this and move the discussion to 56?

**Comment by ianhi** [comment]
Yup!
